services:
  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: acai-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: acai_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - acai-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: acai-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "mysql://root:0000@db:3306/acai_db"
      JWT_SECRET: ${JWT_SECRET}
      zapApiToken: ${zapApiToken}
      zapApiInstance: ${zapApiInstance}
      zapApiClientToken: ${zapApiClientToken}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NODE_ENV: production
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acai-network
    # volumes removidos pois imagens agora v√£o para o Cloudinary

  # Frontend React
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: acai-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - acai-network

networks:
  acai-network:
    driver: bridge

volumes:
  mysql_data: